[02/Dec/2014 13:40:17] ERROR [django.request:231] Internal Server Error: /processoren/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 128, in processoren
    processorenlijst = filters(request,processorenlijst)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 324, in filters
    objectlijst =  pricefilter(objectlijst,minprijs,maxprijs)
  File "/home/robin/Work/School/A-Pc/Website/pcbuilder/views.py", line 353, in pricefilter
    objectlijst.exclude(component)
  File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 676, in exclude
    return self.fields(**fields)
TypeError: fields() keywords must be strings
